// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protos/res.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK  Status = 0
	Status_ERR Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "ERR",
	}
	Status_value = map[string]int32{
		"OK":  0,
		"ERR": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_res_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_res_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{0}
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=wire.Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Fingerprint64 uint64                 `protobuf:"varint,3,opt,name=fingerprint64,proto3" json:"fingerprint64,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*Result_TYPERes
	//	*Result_PINGRes
	//	*Result_ECHORes
	//	*Result_HANDSHAKERes
	//	*Result_EXISTSRes
	//	*Result_GETRes
	//	*Result_SETRes
	//	*Result_DELRes
	//	*Result_KEYSRes
	//	*Result_GETDELRes
	//	*Result_GETEXRes
	//	*Result_GETSETRes
	//	*Result_INCRRes
	//	*Result_DECRRes
	//	*Result_INCRBYRes
	//	*Result_DECRBYRes
	//	*Result_FLUSHDBRes
	//	*Result_EXPIRERes
	//	*Result_EXPIREATRes
	//	*Result_EXPIRETIMERes
	//	*Result_TTLRes
	//	*Result_GETWATCHRes
	//	*Result_UNWATCHRes
	//	*Result_HGETRes
	//	*Result_HSETRes
	//	*Result_HGETALLRes
	//	*Result_HGETWATCHRes
	//	*Result_HGETALLWATCHRes
	//	*Result_ZADDRes
	//	*Result_ZCOUNTRes
	//	*Result_ZRANGERes
	//	*Result_ZPOPMAXRes
	//	*Result_ZREMRes
	//	*Result_ZPOPMINRes
	//	*Result_ZRANKRes
	//	*Result_ZCARDRes
	//	*Result_ZRANGEWATCHRes
	//	*Result_ZCOUNTWATCHRes
	//	*Result_ZCARDWATCHRes
	//	*Result_ZRANKWATCHRes
	//	*Result_GEOADDRes
	//	*Result_GEODISTRes
	//	*Result_GEOSEARCHRes
	Response      isResult_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_protos_res_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OK
}

func (x *Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Result) GetFingerprint64() uint64 {
	if x != nil {
		return x.Fingerprint64
	}
	return 0
}

func (x *Result) GetResponse() isResult_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Result) GetTYPERes() *TYPERes {
	if x != nil {
		if x, ok := x.Response.(*Result_TYPERes); ok {
			return x.TYPERes
		}
	}
	return nil
}

func (x *Result) GetPINGRes() *PINGRes {
	if x != nil {
		if x, ok := x.Response.(*Result_PINGRes); ok {
			return x.PINGRes
		}
	}
	return nil
}

func (x *Result) GetECHORes() *ECHORes {
	if x != nil {
		if x, ok := x.Response.(*Result_ECHORes); ok {
			return x.ECHORes
		}
	}
	return nil
}

func (x *Result) GetHANDSHAKERes() *HANDSHAKERes {
	if x != nil {
		if x, ok := x.Response.(*Result_HANDSHAKERes); ok {
			return x.HANDSHAKERes
		}
	}
	return nil
}

func (x *Result) GetEXISTSRes() *EXISTSRes {
	if x != nil {
		if x, ok := x.Response.(*Result_EXISTSRes); ok {
			return x.EXISTSRes
		}
	}
	return nil
}

func (x *Result) GetGETRes() *GETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GETRes); ok {
			return x.GETRes
		}
	}
	return nil
}

func (x *Result) GetSETRes() *SETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_SETRes); ok {
			return x.SETRes
		}
	}
	return nil
}

func (x *Result) GetDELRes() *DELRes {
	if x != nil {
		if x, ok := x.Response.(*Result_DELRes); ok {
			return x.DELRes
		}
	}
	return nil
}

func (x *Result) GetKEYSRes() *KEYSRes {
	if x != nil {
		if x, ok := x.Response.(*Result_KEYSRes); ok {
			return x.KEYSRes
		}
	}
	return nil
}

func (x *Result) GetGETDELRes() *GETDELRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GETDELRes); ok {
			return x.GETDELRes
		}
	}
	return nil
}

func (x *Result) GetGETEXRes() *GETEXRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GETEXRes); ok {
			return x.GETEXRes
		}
	}
	return nil
}

func (x *Result) GetGETSETRes() *GETSETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GETSETRes); ok {
			return x.GETSETRes
		}
	}
	return nil
}

func (x *Result) GetINCRRes() *INCRRes {
	if x != nil {
		if x, ok := x.Response.(*Result_INCRRes); ok {
			return x.INCRRes
		}
	}
	return nil
}

func (x *Result) GetDECRRes() *DECRRes {
	if x != nil {
		if x, ok := x.Response.(*Result_DECRRes); ok {
			return x.DECRRes
		}
	}
	return nil
}

func (x *Result) GetINCRBYRes() *INCRBYRes {
	if x != nil {
		if x, ok := x.Response.(*Result_INCRBYRes); ok {
			return x.INCRBYRes
		}
	}
	return nil
}

func (x *Result) GetDECRBYRes() *DECRBYRes {
	if x != nil {
		if x, ok := x.Response.(*Result_DECRBYRes); ok {
			return x.DECRBYRes
		}
	}
	return nil
}

func (x *Result) GetFLUSHDBRes() *FLUSHDBRes {
	if x != nil {
		if x, ok := x.Response.(*Result_FLUSHDBRes); ok {
			return x.FLUSHDBRes
		}
	}
	return nil
}

func (x *Result) GetEXPIRERes() *EXPIRERes {
	if x != nil {
		if x, ok := x.Response.(*Result_EXPIRERes); ok {
			return x.EXPIRERes
		}
	}
	return nil
}

func (x *Result) GetEXPIREATRes() *EXPIREATRes {
	if x != nil {
		if x, ok := x.Response.(*Result_EXPIREATRes); ok {
			return x.EXPIREATRes
		}
	}
	return nil
}

func (x *Result) GetEXPIRETIMERes() *EXPIRETIMERes {
	if x != nil {
		if x, ok := x.Response.(*Result_EXPIRETIMERes); ok {
			return x.EXPIRETIMERes
		}
	}
	return nil
}

func (x *Result) GetTTLRes() *TTLRes {
	if x != nil {
		if x, ok := x.Response.(*Result_TTLRes); ok {
			return x.TTLRes
		}
	}
	return nil
}

func (x *Result) GetGETWATCHRes() *GETWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GETWATCHRes); ok {
			return x.GETWATCHRes
		}
	}
	return nil
}

func (x *Result) GetUNWATCHRes() *UNWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_UNWATCHRes); ok {
			return x.UNWATCHRes
		}
	}
	return nil
}

func (x *Result) GetHGETRes() *HGETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_HGETRes); ok {
			return x.HGETRes
		}
	}
	return nil
}

func (x *Result) GetHSETRes() *HSETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_HSETRes); ok {
			return x.HSETRes
		}
	}
	return nil
}

func (x *Result) GetHGETALLRes() *HGETALLRes {
	if x != nil {
		if x, ok := x.Response.(*Result_HGETALLRes); ok {
			return x.HGETALLRes
		}
	}
	return nil
}

func (x *Result) GetHGETWATCHRes() *HGETWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_HGETWATCHRes); ok {
			return x.HGETWATCHRes
		}
	}
	return nil
}

func (x *Result) GetHGETALLWATCHRes() *HGETALLWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_HGETALLWATCHRes); ok {
			return x.HGETALLWATCHRes
		}
	}
	return nil
}

func (x *Result) GetZADDRes() *ZADDRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZADDRes); ok {
			return x.ZADDRes
		}
	}
	return nil
}

func (x *Result) GetZCOUNTRes() *ZCOUNTRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZCOUNTRes); ok {
			return x.ZCOUNTRes
		}
	}
	return nil
}

func (x *Result) GetZRANGERes() *ZRANGERes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZRANGERes); ok {
			return x.ZRANGERes
		}
	}
	return nil
}

func (x *Result) GetZPOPMAXRes() *ZPOPMAXRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZPOPMAXRes); ok {
			return x.ZPOPMAXRes
		}
	}
	return nil
}

func (x *Result) GetZREMRes() *ZREMRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZREMRes); ok {
			return x.ZREMRes
		}
	}
	return nil
}

func (x *Result) GetZPOPMINRes() *ZPOPMINRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZPOPMINRes); ok {
			return x.ZPOPMINRes
		}
	}
	return nil
}

func (x *Result) GetZRANKRes() *ZRANKRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZRANKRes); ok {
			return x.ZRANKRes
		}
	}
	return nil
}

func (x *Result) GetZCARDRes() *ZCARDRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZCARDRes); ok {
			return x.ZCARDRes
		}
	}
	return nil
}

func (x *Result) GetZRANGEWATCHRes() *ZRANGEWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZRANGEWATCHRes); ok {
			return x.ZRANGEWATCHRes
		}
	}
	return nil
}

func (x *Result) GetZCOUNTWATCHRes() *ZCOUNTWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZCOUNTWATCHRes); ok {
			return x.ZCOUNTWATCHRes
		}
	}
	return nil
}

func (x *Result) GetZCARDWATCHRes() *ZCARDWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZCARDWATCHRes); ok {
			return x.ZCARDWATCHRes
		}
	}
	return nil
}

func (x *Result) GetZRANKWATCHRes() *ZRANKWATCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZRANKWATCHRes); ok {
			return x.ZRANKWATCHRes
		}
	}
	return nil
}

func (x *Result) GetGEOADDRes() *GEOADDRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GEOADDRes); ok {
			return x.GEOADDRes
		}
	}
	return nil
}

func (x *Result) GetGEODISTRes() *GEODISTRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GEODISTRes); ok {
			return x.GEODISTRes
		}
	}
	return nil
}

func (x *Result) GetGEOSEARCHRes() *GEOSEARCHRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GEOSEARCHRes); ok {
			return x.GEOSEARCHRes
		}
	}
	return nil
}

type isResult_Response interface {
	isResult_Response()
}

type Result_TYPERes struct {
	TYPERes *TYPERes `protobuf:"bytes,11,opt,name=TYPERes,proto3,oneof"`
}

type Result_PINGRes struct {
	PINGRes *PINGRes `protobuf:"bytes,12,opt,name=PINGRes,proto3,oneof"`
}

type Result_ECHORes struct {
	ECHORes *ECHORes `protobuf:"bytes,13,opt,name=ECHORes,proto3,oneof"`
}

type Result_HANDSHAKERes struct {
	HANDSHAKERes *HANDSHAKERes `protobuf:"bytes,14,opt,name=HANDSHAKERes,proto3,oneof"`
}

type Result_EXISTSRes struct {
	EXISTSRes *EXISTSRes `protobuf:"bytes,15,opt,name=EXISTSRes,proto3,oneof"`
}

type Result_GETRes struct {
	GETRes *GETRes `protobuf:"bytes,16,opt,name=GETRes,proto3,oneof"`
}

type Result_SETRes struct {
	SETRes *SETRes `protobuf:"bytes,17,opt,name=SETRes,proto3,oneof"`
}

type Result_DELRes struct {
	DELRes *DELRes `protobuf:"bytes,18,opt,name=DELRes,proto3,oneof"`
}

type Result_KEYSRes struct {
	KEYSRes *KEYSRes `protobuf:"bytes,19,opt,name=KEYSRes,proto3,oneof"`
}

type Result_GETDELRes struct {
	GETDELRes *GETDELRes `protobuf:"bytes,20,opt,name=GETDELRes,proto3,oneof"`
}

type Result_GETEXRes struct {
	GETEXRes *GETEXRes `protobuf:"bytes,21,opt,name=GETEXRes,proto3,oneof"`
}

type Result_GETSETRes struct {
	GETSETRes *GETSETRes `protobuf:"bytes,22,opt,name=GETSETRes,proto3,oneof"`
}

type Result_INCRRes struct {
	INCRRes *INCRRes `protobuf:"bytes,23,opt,name=INCRRes,proto3,oneof"`
}

type Result_DECRRes struct {
	DECRRes *DECRRes `protobuf:"bytes,24,opt,name=DECRRes,proto3,oneof"`
}

type Result_INCRBYRes struct {
	INCRBYRes *INCRBYRes `protobuf:"bytes,25,opt,name=INCRBYRes,proto3,oneof"`
}

type Result_DECRBYRes struct {
	DECRBYRes *DECRBYRes `protobuf:"bytes,26,opt,name=DECRBYRes,proto3,oneof"`
}

type Result_FLUSHDBRes struct {
	FLUSHDBRes *FLUSHDBRes `protobuf:"bytes,27,opt,name=FLUSHDBRes,proto3,oneof"`
}

type Result_EXPIRERes struct {
	EXPIRERes *EXPIRERes `protobuf:"bytes,28,opt,name=EXPIRERes,proto3,oneof"`
}

type Result_EXPIREATRes struct {
	EXPIREATRes *EXPIREATRes `protobuf:"bytes,29,opt,name=EXPIREATRes,proto3,oneof"`
}

type Result_EXPIRETIMERes struct {
	EXPIRETIMERes *EXPIRETIMERes `protobuf:"bytes,30,opt,name=EXPIRETIMERes,proto3,oneof"`
}

type Result_TTLRes struct {
	TTLRes *TTLRes `protobuf:"bytes,31,opt,name=TTLRes,proto3,oneof"`
}

type Result_GETWATCHRes struct {
	GETWATCHRes *GETWATCHRes `protobuf:"bytes,32,opt,name=GETWATCHRes,proto3,oneof"`
}

type Result_UNWATCHRes struct {
	UNWATCHRes *UNWATCHRes `protobuf:"bytes,33,opt,name=UNWATCHRes,proto3,oneof"`
}

type Result_HGETRes struct {
	HGETRes *HGETRes `protobuf:"bytes,34,opt,name=HGETRes,proto3,oneof"`
}

type Result_HSETRes struct {
	HSETRes *HSETRes `protobuf:"bytes,35,opt,name=HSETRes,proto3,oneof"`
}

type Result_HGETALLRes struct {
	HGETALLRes *HGETALLRes `protobuf:"bytes,36,opt,name=HGETALLRes,proto3,oneof"`
}

type Result_HGETWATCHRes struct {
	HGETWATCHRes *HGETWATCHRes `protobuf:"bytes,37,opt,name=HGETWATCHRes,proto3,oneof"`
}

type Result_HGETALLWATCHRes struct {
	HGETALLWATCHRes *HGETALLWATCHRes `protobuf:"bytes,38,opt,name=HGETALLWATCHRes,proto3,oneof"`
}

type Result_ZADDRes struct {
	ZADDRes *ZADDRes `protobuf:"bytes,39,opt,name=ZADDRes,proto3,oneof"`
}

type Result_ZCOUNTRes struct {
	ZCOUNTRes *ZCOUNTRes `protobuf:"bytes,40,opt,name=ZCOUNTRes,proto3,oneof"`
}

type Result_ZRANGERes struct {
	ZRANGERes *ZRANGERes `protobuf:"bytes,41,opt,name=ZRANGERes,proto3,oneof"`
}

type Result_ZPOPMAXRes struct {
	ZPOPMAXRes *ZPOPMAXRes `protobuf:"bytes,42,opt,name=ZPOPMAXRes,proto3,oneof"`
}

type Result_ZREMRes struct {
	ZREMRes *ZREMRes `protobuf:"bytes,43,opt,name=ZREMRes,proto3,oneof"`
}

type Result_ZPOPMINRes struct {
	ZPOPMINRes *ZPOPMINRes `protobuf:"bytes,44,opt,name=ZPOPMINRes,proto3,oneof"`
}

type Result_ZRANKRes struct {
	ZRANKRes *ZRANKRes `protobuf:"bytes,45,opt,name=ZRANKRes,proto3,oneof"`
}

type Result_ZCARDRes struct {
	ZCARDRes *ZCARDRes `protobuf:"bytes,46,opt,name=ZCARDRes,proto3,oneof"`
}

type Result_ZRANGEWATCHRes struct {
	ZRANGEWATCHRes *ZRANGEWATCHRes `protobuf:"bytes,47,opt,name=ZRANGEWATCHRes,proto3,oneof"`
}

type Result_ZCOUNTWATCHRes struct {
	ZCOUNTWATCHRes *ZCOUNTWATCHRes `protobuf:"bytes,48,opt,name=ZCOUNTWATCHRes,proto3,oneof"`
}

type Result_ZCARDWATCHRes struct {
	ZCARDWATCHRes *ZCARDWATCHRes `protobuf:"bytes,49,opt,name=ZCARDWATCHRes,proto3,oneof"`
}

type Result_ZRANKWATCHRes struct {
	ZRANKWATCHRes *ZRANKWATCHRes `protobuf:"bytes,50,opt,name=ZRANKWATCHRes,proto3,oneof"`
}

type Result_GEOADDRes struct {
	GEOADDRes *GEOADDRes `protobuf:"bytes,51,opt,name=GEOADDRes,proto3,oneof"`
}

type Result_GEODISTRes struct {
	GEODISTRes *GEODISTRes `protobuf:"bytes,52,opt,name=GEODISTRes,proto3,oneof"`
}

type Result_GEOSEARCHRes struct {
	GEOSEARCHRes *GEOSEARCHRes `protobuf:"bytes,53,opt,name=GEOSEARCHRes,proto3,oneof"`
}

func (*Result_TYPERes) isResult_Response() {}

func (*Result_PINGRes) isResult_Response() {}

func (*Result_ECHORes) isResult_Response() {}

func (*Result_HANDSHAKERes) isResult_Response() {}

func (*Result_EXISTSRes) isResult_Response() {}

func (*Result_GETRes) isResult_Response() {}

func (*Result_SETRes) isResult_Response() {}

func (*Result_DELRes) isResult_Response() {}

func (*Result_KEYSRes) isResult_Response() {}

func (*Result_GETDELRes) isResult_Response() {}

func (*Result_GETEXRes) isResult_Response() {}

func (*Result_GETSETRes) isResult_Response() {}

func (*Result_INCRRes) isResult_Response() {}

func (*Result_DECRRes) isResult_Response() {}

func (*Result_INCRBYRes) isResult_Response() {}

func (*Result_DECRBYRes) isResult_Response() {}

func (*Result_FLUSHDBRes) isResult_Response() {}

func (*Result_EXPIRERes) isResult_Response() {}

func (*Result_EXPIREATRes) isResult_Response() {}

func (*Result_EXPIRETIMERes) isResult_Response() {}

func (*Result_TTLRes) isResult_Response() {}

func (*Result_GETWATCHRes) isResult_Response() {}

func (*Result_UNWATCHRes) isResult_Response() {}

func (*Result_HGETRes) isResult_Response() {}

func (*Result_HSETRes) isResult_Response() {}

func (*Result_HGETALLRes) isResult_Response() {}

func (*Result_HGETWATCHRes) isResult_Response() {}

func (*Result_HGETALLWATCHRes) isResult_Response() {}

func (*Result_ZADDRes) isResult_Response() {}

func (*Result_ZCOUNTRes) isResult_Response() {}

func (*Result_ZRANGERes) isResult_Response() {}

func (*Result_ZPOPMAXRes) isResult_Response() {}

func (*Result_ZREMRes) isResult_Response() {}

func (*Result_ZPOPMINRes) isResult_Response() {}

func (*Result_ZRANKRes) isResult_Response() {}

func (*Result_ZCARDRes) isResult_Response() {}

func (*Result_ZRANGEWATCHRes) isResult_Response() {}

func (*Result_ZCOUNTWATCHRes) isResult_Response() {}

func (*Result_ZCARDWATCHRes) isResult_Response() {}

func (*Result_ZRANKWATCHRes) isResult_Response() {}

func (*Result_GEOADDRes) isResult_Response() {}

func (*Result_GEODISTRes) isResult_Response() {}

func (*Result_GEOSEARCHRes) isResult_Response() {}

type ZRANKWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZRANKWATCHRes) Reset() {
	*x = ZRANKWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZRANKWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRANKWATCHRes) ProtoMessage() {}

func (x *ZRANKWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRANKWATCHRes.ProtoReflect.Descriptor instead.
func (*ZRANKWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{1}
}

type HGETWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGETWATCHRes) Reset() {
	*x = HGETWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGETWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGETWATCHRes) ProtoMessage() {}

func (x *HGETWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGETWATCHRes.ProtoReflect.Descriptor instead.
func (*HGETWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{2}
}

type HGETALLWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGETALLWATCHRes) Reset() {
	*x = HGETALLWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGETALLWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGETALLWATCHRes) ProtoMessage() {}

func (x *HGETALLWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGETALLWATCHRes.ProtoReflect.Descriptor instead.
func (*HGETALLWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{3}
}

type GETWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETWATCHRes) Reset() {
	*x = GETWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETWATCHRes) ProtoMessage() {}

func (x *GETWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETWATCHRes.ProtoReflect.Descriptor instead.
func (*GETWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{4}
}

type UNWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UNWATCHRes) Reset() {
	*x = UNWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UNWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UNWATCHRes) ProtoMessage() {}

func (x *UNWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UNWATCHRes.ProtoReflect.Descriptor instead.
func (*UNWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{5}
}

type ZADDRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZADDRes) Reset() {
	*x = ZADDRes{}
	mi := &file_protos_res_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZADDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZADDRes) ProtoMessage() {}

func (x *ZADDRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZADDRes.ProtoReflect.Descriptor instead.
func (*ZADDRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{6}
}

func (x *ZADDRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ZCOUNTRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZCOUNTRes) Reset() {
	*x = ZCOUNTRes{}
	mi := &file_protos_res_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZCOUNTRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCOUNTRes) ProtoMessage() {}

func (x *ZCOUNTRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCOUNTRes.ProtoReflect.Descriptor instead.
func (*ZCOUNTRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{7}
}

func (x *ZCOUNTRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TYPERes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TYPERes) Reset() {
	*x = TYPERes{}
	mi := &file_protos_res_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TYPERes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TYPERes) ProtoMessage() {}

func (x *TYPERes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TYPERes.ProtoReflect.Descriptor instead.
func (*TYPERes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{8}
}

func (x *TYPERes) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type PINGRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PINGRes) Reset() {
	*x = PINGRes{}
	mi := &file_protos_res_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PINGRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PINGRes) ProtoMessage() {}

func (x *PINGRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PINGRes.ProtoReflect.Descriptor instead.
func (*PINGRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{9}
}

func (x *PINGRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HGETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGETRes) Reset() {
	*x = HGETRes{}
	mi := &file_protos_res_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGETRes) ProtoMessage() {}

func (x *HGETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGETRes.ProtoReflect.Descriptor instead.
func (*HGETRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{10}
}

func (x *HGETRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HSETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HSETRes) Reset() {
	*x = HSETRes{}
	mi := &file_protos_res_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSETRes) ProtoMessage() {}

func (x *HSETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSETRes.ProtoReflect.Descriptor instead.
func (*HSETRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{11}
}

func (x *HSETRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type HElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HElement) Reset() {
	*x = HElement{}
	mi := &file_protos_res_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HElement) ProtoMessage() {}

func (x *HElement) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HElement.ProtoReflect.Descriptor instead.
func (*HElement) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{12}
}

func (x *HElement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HElement) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HGETALLRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*HElement            `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGETALLRes) Reset() {
	*x = HGETALLRes{}
	mi := &file_protos_res_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGETALLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGETALLRes) ProtoMessage() {}

func (x *HGETALLRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGETALLRes.ProtoReflect.Descriptor instead.
func (*HGETALLRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{13}
}

func (x *HGETALLRes) GetElements() []*HElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type TTLRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTLRes) Reset() {
	*x = TTLRes{}
	mi := &file_protos_res_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTLRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTLRes) ProtoMessage() {}

func (x *TTLRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTLRes.ProtoReflect.Descriptor instead.
func (*TTLRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{14}
}

func (x *TTLRes) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type EXPIRERes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsChanged     bool                   `protobuf:"varint,1,opt,name=is_changed,json=isChanged,proto3" json:"is_changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EXPIRERes) Reset() {
	*x = EXPIRERes{}
	mi := &file_protos_res_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EXPIRERes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EXPIRERes) ProtoMessage() {}

func (x *EXPIRERes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EXPIRERes.ProtoReflect.Descriptor instead.
func (*EXPIRERes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{15}
}

func (x *EXPIRERes) GetIsChanged() bool {
	if x != nil {
		return x.IsChanged
	}
	return false
}

type EXPIREATRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsChanged     bool                   `protobuf:"varint,1,opt,name=is_changed,json=isChanged,proto3" json:"is_changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EXPIREATRes) Reset() {
	*x = EXPIREATRes{}
	mi := &file_protos_res_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EXPIREATRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EXPIREATRes) ProtoMessage() {}

func (x *EXPIREATRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EXPIREATRes.ProtoReflect.Descriptor instead.
func (*EXPIREATRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{16}
}

func (x *EXPIREATRes) GetIsChanged() bool {
	if x != nil {
		return x.IsChanged
	}
	return false
}

type EXPIRETIMERes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixSec       int64                  `protobuf:"varint,1,opt,name=unix_sec,json=unixSec,proto3" json:"unix_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EXPIRETIMERes) Reset() {
	*x = EXPIRETIMERes{}
	mi := &file_protos_res_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EXPIRETIMERes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EXPIRETIMERes) ProtoMessage() {}

func (x *EXPIRETIMERes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EXPIRETIMERes.ProtoReflect.Descriptor instead.
func (*EXPIRETIMERes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{17}
}

func (x *EXPIRETIMERes) GetUnixSec() int64 {
	if x != nil {
		return x.UnixSec
	}
	return 0
}

type ECHORes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECHORes) Reset() {
	*x = ECHORes{}
	mi := &file_protos_res_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECHORes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECHORes) ProtoMessage() {}

func (x *ECHORes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECHORes.ProtoReflect.Descriptor instead.
func (*ECHORes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{18}
}

func (x *ECHORes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EXISTSRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EXISTSRes) Reset() {
	*x = EXISTSRes{}
	mi := &file_protos_res_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EXISTSRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EXISTSRes) ProtoMessage() {}

func (x *EXISTSRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EXISTSRes.ProtoReflect.Descriptor instead.
func (*EXISTSRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{19}
}

func (x *EXISTSRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type HANDSHAKERes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HANDSHAKERes) Reset() {
	*x = HANDSHAKERes{}
	mi := &file_protos_res_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HANDSHAKERes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HANDSHAKERes) ProtoMessage() {}

func (x *HANDSHAKERes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HANDSHAKERes.ProtoReflect.Descriptor instead.
func (*HANDSHAKERes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{20}
}

type GETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETRes) Reset() {
	*x = GETRes{}
	mi := &file_protos_res_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETRes) ProtoMessage() {}

func (x *GETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETRes.ProtoReflect.Descriptor instead.
func (*GETRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{21}
}

func (x *GETRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GETEXRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETEXRes) Reset() {
	*x = GETEXRes{}
	mi := &file_protos_res_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETEXRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETEXRes) ProtoMessage() {}

func (x *GETEXRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETEXRes.ProtoReflect.Descriptor instead.
func (*GETEXRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{22}
}

func (x *GETEXRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GETSETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETSETRes) Reset() {
	*x = GETSETRes{}
	mi := &file_protos_res_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETSETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETSETRes) ProtoMessage() {}

func (x *GETSETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETSETRes.ProtoReflect.Descriptor instead.
func (*GETSETRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{23}
}

func (x *GETSETRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GETDELRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETDELRes) Reset() {
	*x = GETDELRes{}
	mi := &file_protos_res_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETDELRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETDELRes) ProtoMessage() {}

func (x *GETDELRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETDELRes.ProtoReflect.Descriptor instead.
func (*GETDELRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{24}
}

func (x *GETDELRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SETRes) Reset() {
	*x = SETRes{}
	mi := &file_protos_res_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SETRes) ProtoMessage() {}

func (x *SETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SETRes.ProtoReflect.Descriptor instead.
func (*SETRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{25}
}

type DELRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DELRes) Reset() {
	*x = DELRes{}
	mi := &file_protos_res_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DELRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DELRes) ProtoMessage() {}

func (x *DELRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DELRes.ProtoReflect.Descriptor instead.
func (*DELRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{26}
}

func (x *DELRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FLUSHDBRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FLUSHDBRes) Reset() {
	*x = FLUSHDBRes{}
	mi := &file_protos_res_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FLUSHDBRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FLUSHDBRes) ProtoMessage() {}

func (x *FLUSHDBRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FLUSHDBRes.ProtoReflect.Descriptor instead.
func (*FLUSHDBRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{27}
}

type KEYSRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KEYSRes) Reset() {
	*x = KEYSRes{}
	mi := &file_protos_res_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KEYSRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KEYSRes) ProtoMessage() {}

func (x *KEYSRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KEYSRes.ProtoReflect.Descriptor instead.
func (*KEYSRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{28}
}

func (x *KEYSRes) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type INCRRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INCRRes) Reset() {
	*x = INCRRes{}
	mi := &file_protos_res_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INCRRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INCRRes) ProtoMessage() {}

func (x *INCRRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INCRRes.ProtoReflect.Descriptor instead.
func (*INCRRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{29}
}

func (x *INCRRes) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DECRRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DECRRes) Reset() {
	*x = DECRRes{}
	mi := &file_protos_res_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DECRRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DECRRes) ProtoMessage() {}

func (x *DECRRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DECRRes.ProtoReflect.Descriptor instead.
func (*DECRRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{30}
}

func (x *DECRRes) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type INCRBYRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *INCRBYRes) Reset() {
	*x = INCRBYRes{}
	mi := &file_protos_res_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *INCRBYRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INCRBYRes) ProtoMessage() {}

func (x *INCRBYRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INCRBYRes.ProtoReflect.Descriptor instead.
func (*INCRBYRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{31}
}

func (x *INCRBYRes) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type DECRBYRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DECRBYRes) Reset() {
	*x = DECRBYRes{}
	mi := &file_protos_res_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DECRBYRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DECRBYRes) ProtoMessage() {}

func (x *DECRBYRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DECRBYRes.ProtoReflect.Descriptor instead.
func (*DECRBYRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{32}
}

func (x *DECRBYRes) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ZElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	Rank          int64                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZElement) Reset() {
	*x = ZElement{}
	mi := &file_protos_res_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZElement) ProtoMessage() {}

func (x *ZElement) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZElement.ProtoReflect.Descriptor instead.
func (*ZElement) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{33}
}

func (x *ZElement) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ZElement) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *ZElement) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type ZRANGERes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*ZElement            `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZRANGERes) Reset() {
	*x = ZRANGERes{}
	mi := &file_protos_res_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZRANGERes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRANGERes) ProtoMessage() {}

func (x *ZRANGERes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRANGERes.ProtoReflect.Descriptor instead.
func (*ZRANGERes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{34}
}

func (x *ZRANGERes) GetElements() []*ZElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ZPOPMAXRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*ZElement            `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZPOPMAXRes) Reset() {
	*x = ZPOPMAXRes{}
	mi := &file_protos_res_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZPOPMAXRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZPOPMAXRes) ProtoMessage() {}

func (x *ZPOPMAXRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZPOPMAXRes.ProtoReflect.Descriptor instead.
func (*ZPOPMAXRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{35}
}

func (x *ZPOPMAXRes) GetElements() []*ZElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ZREMRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZREMRes) Reset() {
	*x = ZREMRes{}
	mi := &file_protos_res_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZREMRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZREMRes) ProtoMessage() {}

func (x *ZREMRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZREMRes.ProtoReflect.Descriptor instead.
func (*ZREMRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{36}
}

func (x *ZREMRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ZPOPMINRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*ZElement            `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZPOPMINRes) Reset() {
	*x = ZPOPMINRes{}
	mi := &file_protos_res_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZPOPMINRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZPOPMINRes) ProtoMessage() {}

func (x *ZPOPMINRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZPOPMINRes.ProtoReflect.Descriptor instead.
func (*ZPOPMINRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{37}
}

func (x *ZPOPMINRes) GetElements() []*ZElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ZRANKRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Element       *ZElement              `protobuf:"bytes,2,opt,name=element,proto3" json:"element,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZRANKRes) Reset() {
	*x = ZRANKRes{}
	mi := &file_protos_res_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZRANKRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRANKRes) ProtoMessage() {}

func (x *ZRANKRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRANKRes.ProtoReflect.Descriptor instead.
func (*ZRANKRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{38}
}

func (x *ZRANKRes) GetElement() *ZElement {
	if x != nil {
		return x.Element
	}
	return nil
}

type ZCARDRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZCARDRes) Reset() {
	*x = ZCARDRes{}
	mi := &file_protos_res_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZCARDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCARDRes) ProtoMessage() {}

func (x *ZCARDRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCARDRes.ProtoReflect.Descriptor instead.
func (*ZCARDRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{39}
}

func (x *ZCARDRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ZRANGEWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZRANGEWATCHRes) Reset() {
	*x = ZRANGEWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZRANGEWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRANGEWATCHRes) ProtoMessage() {}

func (x *ZRANGEWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRANGEWATCHRes.ProtoReflect.Descriptor instead.
func (*ZRANGEWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{40}
}

type ZCOUNTWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZCOUNTWATCHRes) Reset() {
	*x = ZCOUNTWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZCOUNTWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCOUNTWATCHRes) ProtoMessage() {}

func (x *ZCOUNTWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCOUNTWATCHRes.ProtoReflect.Descriptor instead.
func (*ZCOUNTWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{41}
}

type ZCARDWATCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZCARDWATCHRes) Reset() {
	*x = ZCARDWATCHRes{}
	mi := &file_protos_res_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZCARDWATCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZCARDWATCHRes) ProtoMessage() {}

func (x *ZCARDWATCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZCARDWATCHRes.ProtoReflect.Descriptor instead.
func (*ZCARDWATCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{42}
}

type GEOADDRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GEOADDRes) Reset() {
	*x = GEOADDRes{}
	mi := &file_protos_res_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GEOADDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEOADDRes) ProtoMessage() {}

func (x *GEOADDRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEOADDRes.ProtoReflect.Descriptor instead.
func (*GEOADDRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{43}
}

func (x *GEOADDRes) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GEODISTRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Distance      float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GEODISTRes) Reset() {
	*x = GEODISTRes{}
	mi := &file_protos_res_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GEODISTRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEODISTRes) ProtoMessage() {}

func (x *GEODISTRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEODISTRes.ProtoReflect.Descriptor instead.
func (*GEODISTRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{44}
}

func (x *GEODISTRes) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type GEOCoordinates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GEOCoordinates) Reset() {
	*x = GEOCoordinates{}
	mi := &file_protos_res_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GEOCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEOCoordinates) ProtoMessage() {}

func (x *GEOCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEOCoordinates.ProtoReflect.Descriptor instead.
func (*GEOCoordinates) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{45}
}

func (x *GEOCoordinates) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GEOCoordinates) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type GEOElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        string                 `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Coordinates   *GEOCoordinates        `protobuf:"bytes,2,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Distance      float64                `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Hash          uint64                 `protobuf:"varint,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Rank          int64                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GEOElement) Reset() {
	*x = GEOElement{}
	mi := &file_protos_res_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GEOElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEOElement) ProtoMessage() {}

func (x *GEOElement) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEOElement.ProtoReflect.Descriptor instead.
func (*GEOElement) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{46}
}

func (x *GEOElement) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

func (x *GEOElement) GetCoordinates() *GEOCoordinates {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *GEOElement) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *GEOElement) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *GEOElement) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GEOSEARCHRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*GEOElement          `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GEOSEARCHRes) Reset() {
	*x = GEOSEARCHRes{}
	mi := &file_protos_res_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GEOSEARCHRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GEOSEARCHRes) ProtoMessage() {}

func (x *GEOSEARCHRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GEOSEARCHRes.ProtoReflect.Descriptor instead.
func (*GEOSEARCHRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{47}
}

func (x *GEOSEARCHRes) GetElements() []*GEOElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

var File_protos_res_proto protoreflect.FileDescriptor

const file_protos_res_proto_rawDesc = "" +
	"\n" +
	"\x10protos/res.proto\x12\x04wire\"\xd9\x11\n" +
	"\x06Result\x12$\n" +
	"\x06status\x18\x01 \x01(\x0e2\f.wire.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\rfingerprint64\x18\x03 \x01(\x04R\rfingerprint64\x12)\n" +
	"\aTYPERes\x18\v \x01(\v2\r.wire.TYPEResH\x00R\aTYPERes\x12)\n" +
	"\aPINGRes\x18\f \x01(\v2\r.wire.PINGResH\x00R\aPINGRes\x12)\n" +
	"\aECHORes\x18\r \x01(\v2\r.wire.ECHOResH\x00R\aECHORes\x128\n" +
	"\fHANDSHAKERes\x18\x0e \x01(\v2\x12.wire.HANDSHAKEResH\x00R\fHANDSHAKERes\x12/\n" +
	"\tEXISTSRes\x18\x0f \x01(\v2\x0f.wire.EXISTSResH\x00R\tEXISTSRes\x12&\n" +
	"\x06GETRes\x18\x10 \x01(\v2\f.wire.GETResH\x00R\x06GETRes\x12&\n" +
	"\x06SETRes\x18\x11 \x01(\v2\f.wire.SETResH\x00R\x06SETRes\x12&\n" +
	"\x06DELRes\x18\x12 \x01(\v2\f.wire.DELResH\x00R\x06DELRes\x12)\n" +
	"\aKEYSRes\x18\x13 \x01(\v2\r.wire.KEYSResH\x00R\aKEYSRes\x12/\n" +
	"\tGETDELRes\x18\x14 \x01(\v2\x0f.wire.GETDELResH\x00R\tGETDELRes\x12,\n" +
	"\bGETEXRes\x18\x15 \x01(\v2\x0e.wire.GETEXResH\x00R\bGETEXRes\x12/\n" +
	"\tGETSETRes\x18\x16 \x01(\v2\x0f.wire.GETSETResH\x00R\tGETSETRes\x12)\n" +
	"\aINCRRes\x18\x17 \x01(\v2\r.wire.INCRResH\x00R\aINCRRes\x12)\n" +
	"\aDECRRes\x18\x18 \x01(\v2\r.wire.DECRResH\x00R\aDECRRes\x12/\n" +
	"\tINCRBYRes\x18\x19 \x01(\v2\x0f.wire.INCRBYResH\x00R\tINCRBYRes\x12/\n" +
	"\tDECRBYRes\x18\x1a \x01(\v2\x0f.wire.DECRBYResH\x00R\tDECRBYRes\x122\n" +
	"\n" +
	"FLUSHDBRes\x18\x1b \x01(\v2\x10.wire.FLUSHDBResH\x00R\n" +
	"FLUSHDBRes\x12/\n" +
	"\tEXPIRERes\x18\x1c \x01(\v2\x0f.wire.EXPIREResH\x00R\tEXPIRERes\x125\n" +
	"\vEXPIREATRes\x18\x1d \x01(\v2\x11.wire.EXPIREATResH\x00R\vEXPIREATRes\x12;\n" +
	"\rEXPIRETIMERes\x18\x1e \x01(\v2\x13.wire.EXPIRETIMEResH\x00R\rEXPIRETIMERes\x12&\n" +
	"\x06TTLRes\x18\x1f \x01(\v2\f.wire.TTLResH\x00R\x06TTLRes\x125\n" +
	"\vGETWATCHRes\x18  \x01(\v2\x11.wire.GETWATCHResH\x00R\vGETWATCHRes\x122\n" +
	"\n" +
	"UNWATCHRes\x18! \x01(\v2\x10.wire.UNWATCHResH\x00R\n" +
	"UNWATCHRes\x12)\n" +
	"\aHGETRes\x18\" \x01(\v2\r.wire.HGETResH\x00R\aHGETRes\x12)\n" +
	"\aHSETRes\x18# \x01(\v2\r.wire.HSETResH\x00R\aHSETRes\x122\n" +
	"\n" +
	"HGETALLRes\x18$ \x01(\v2\x10.wire.HGETALLResH\x00R\n" +
	"HGETALLRes\x128\n" +
	"\fHGETWATCHRes\x18% \x01(\v2\x12.wire.HGETWATCHResH\x00R\fHGETWATCHRes\x12A\n" +
	"\x0fHGETALLWATCHRes\x18& \x01(\v2\x15.wire.HGETALLWATCHResH\x00R\x0fHGETALLWATCHRes\x12)\n" +
	"\aZADDRes\x18' \x01(\v2\r.wire.ZADDResH\x00R\aZADDRes\x12/\n" +
	"\tZCOUNTRes\x18( \x01(\v2\x0f.wire.ZCOUNTResH\x00R\tZCOUNTRes\x12/\n" +
	"\tZRANGERes\x18) \x01(\v2\x0f.wire.ZRANGEResH\x00R\tZRANGERes\x122\n" +
	"\n" +
	"ZPOPMAXRes\x18* \x01(\v2\x10.wire.ZPOPMAXResH\x00R\n" +
	"ZPOPMAXRes\x12)\n" +
	"\aZREMRes\x18+ \x01(\v2\r.wire.ZREMResH\x00R\aZREMRes\x122\n" +
	"\n" +
	"ZPOPMINRes\x18, \x01(\v2\x10.wire.ZPOPMINResH\x00R\n" +
	"ZPOPMINRes\x12,\n" +
	"\bZRANKRes\x18- \x01(\v2\x0e.wire.ZRANKResH\x00R\bZRANKRes\x12,\n" +
	"\bZCARDRes\x18. \x01(\v2\x0e.wire.ZCARDResH\x00R\bZCARDRes\x12>\n" +
	"\x0eZRANGEWATCHRes\x18/ \x01(\v2\x14.wire.ZRANGEWATCHResH\x00R\x0eZRANGEWATCHRes\x12>\n" +
	"\x0eZCOUNTWATCHRes\x180 \x01(\v2\x14.wire.ZCOUNTWATCHResH\x00R\x0eZCOUNTWATCHRes\x12;\n" +
	"\rZCARDWATCHRes\x181 \x01(\v2\x13.wire.ZCARDWATCHResH\x00R\rZCARDWATCHRes\x12;\n" +
	"\rZRANKWATCHRes\x182 \x01(\v2\x13.wire.ZRANKWATCHResH\x00R\rZRANKWATCHRes\x12/\n" +
	"\tGEOADDRes\x183 \x01(\v2\x0f.wire.GEOADDResH\x00R\tGEOADDRes\x122\n" +
	"\n" +
	"GEODISTRes\x184 \x01(\v2\x10.wire.GEODISTResH\x00R\n" +
	"GEODISTRes\x128\n" +
	"\fGEOSEARCHRes\x185 \x01(\v2\x12.wire.GEOSEARCHResH\x00R\fGEOSEARCHResB\n" +
	"\n" +
	"\bresponse\"\x0f\n" +
	"\rZRANKWATCHRes\"\x0e\n" +
	"\fHGETWATCHRes\"\x11\n" +
	"\x0fHGETALLWATCHRes\"\r\n" +
	"\vGETWATCHRes\"\f\n" +
	"\n" +
	"UNWATCHRes\"\x1f\n" +
	"\aZADDRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"!\n" +
	"\tZCOUNTRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x1d\n" +
	"\aTYPERes\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"#\n" +
	"\aPINGRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1f\n" +
	"\aHGETRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1f\n" +
	"\aHSETRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"2\n" +
	"\bHElement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"8\n" +
	"\n" +
	"HGETALLRes\x12*\n" +
	"\belements\x18\x01 \x03(\v2\x0e.wire.HElementR\belements\"\"\n" +
	"\x06TTLRes\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\"*\n" +
	"\tEXPIRERes\x12\x1d\n" +
	"\n" +
	"is_changed\x18\x01 \x01(\bR\tisChanged\",\n" +
	"\vEXPIREATRes\x12\x1d\n" +
	"\n" +
	"is_changed\x18\x01 \x01(\bR\tisChanged\"*\n" +
	"\rEXPIRETIMERes\x12\x19\n" +
	"\bunix_sec\x18\x01 \x01(\x03R\aunixSec\"#\n" +
	"\aECHORes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"!\n" +
	"\tEXISTSRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x0e\n" +
	"\fHANDSHAKERes\"\x1e\n" +
	"\x06GETRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\" \n" +
	"\bGETEXRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\tGETSETRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"!\n" +
	"\tGETDELRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\b\n" +
	"\x06SETRes\"\x1e\n" +
	"\x06DELRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\f\n" +
	"\n" +
	"FLUSHDBRes\"\x1d\n" +
	"\aKEYSRes\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\x1f\n" +
	"\aINCRRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"\x1f\n" +
	"\aDECRRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"!\n" +
	"\tINCRBYRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"!\n" +
	"\tDECRBYRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\"L\n" +
	"\bZElement\x12\x14\n" +
	"\x05score\x18\x01 \x01(\x03R\x05score\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x03R\x04rank\"7\n" +
	"\tZRANGERes\x12*\n" +
	"\belements\x18\x01 \x03(\v2\x0e.wire.ZElementR\belements\"8\n" +
	"\n" +
	"ZPOPMAXRes\x12*\n" +
	"\belements\x18\x01 \x03(\v2\x0e.wire.ZElementR\belements\"\x1f\n" +
	"\aZREMRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"8\n" +
	"\n" +
	"ZPOPMINRes\x12*\n" +
	"\belements\x18\x01 \x03(\v2\x0e.wire.ZElementR\belements\"4\n" +
	"\bZRANKRes\x12(\n" +
	"\aelement\x18\x02 \x01(\v2\x0e.wire.ZElementR\aelement\" \n" +
	"\bZCARDRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\x10\n" +
	"\x0eZRANGEWATCHRes\"\x10\n" +
	"\x0eZCOUNTWATCHRes\"\x0f\n" +
	"\rZCARDWATCHRes\"!\n" +
	"\tGEOADDRes\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"(\n" +
	"\n" +
	"GEODISTRes\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x01R\bdistance\"J\n" +
	"\x0eGEOCoordinates\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"\xa0\x01\n" +
	"\n" +
	"GEOElement\x12\x16\n" +
	"\x06member\x18\x01 \x01(\tR\x06member\x126\n" +
	"\vcoordinates\x18\x02 \x01(\v2\x14.wire.GEOCoordinatesR\vcoordinates\x12\x1a\n" +
	"\bdistance\x18\x03 \x01(\x01R\bdistance\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\x04R\x04hash\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x03R\x04rank\"<\n" +
	"\fGEOSEARCHRes\x12,\n" +
	"\belements\x18\x01 \x03(\v2\x10.wire.GEOElementR\belements*\x19\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\a\n" +
	"\x03ERR\x10\x01B\bZ\x06./wireb\x06proto3"

var (
	file_protos_res_proto_rawDescOnce sync.Once
	file_protos_res_proto_rawDescData []byte
)

func file_protos_res_proto_rawDescGZIP() []byte {
	file_protos_res_proto_rawDescOnce.Do(func() {
		file_protos_res_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_res_proto_rawDesc), len(file_protos_res_proto_rawDesc)))
	})
	return file_protos_res_proto_rawDescData
}

var file_protos_res_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_res_proto_msgTypes = make([]protoimpl.MessageInfo, 48)
var file_protos_res_proto_goTypes = []any{
	(Status)(0),             // 0: wire.Status
	(*Result)(nil),          // 1: wire.Result
	(*ZRANKWATCHRes)(nil),   // 2: wire.ZRANKWATCHRes
	(*HGETWATCHRes)(nil),    // 3: wire.HGETWATCHRes
	(*HGETALLWATCHRes)(nil), // 4: wire.HGETALLWATCHRes
	(*GETWATCHRes)(nil),     // 5: wire.GETWATCHRes
	(*UNWATCHRes)(nil),      // 6: wire.UNWATCHRes
	(*ZADDRes)(nil),         // 7: wire.ZADDRes
	(*ZCOUNTRes)(nil),       // 8: wire.ZCOUNTRes
	(*TYPERes)(nil),         // 9: wire.TYPERes
	(*PINGRes)(nil),         // 10: wire.PINGRes
	(*HGETRes)(nil),         // 11: wire.HGETRes
	(*HSETRes)(nil),         // 12: wire.HSETRes
	(*HElement)(nil),        // 13: wire.HElement
	(*HGETALLRes)(nil),      // 14: wire.HGETALLRes
	(*TTLRes)(nil),          // 15: wire.TTLRes
	(*EXPIRERes)(nil),       // 16: wire.EXPIRERes
	(*EXPIREATRes)(nil),     // 17: wire.EXPIREATRes
	(*EXPIRETIMERes)(nil),   // 18: wire.EXPIRETIMERes
	(*ECHORes)(nil),         // 19: wire.ECHORes
	(*EXISTSRes)(nil),       // 20: wire.EXISTSRes
	(*HANDSHAKERes)(nil),    // 21: wire.HANDSHAKERes
	(*GETRes)(nil),          // 22: wire.GETRes
	(*GETEXRes)(nil),        // 23: wire.GETEXRes
	(*GETSETRes)(nil),       // 24: wire.GETSETRes
	(*GETDELRes)(nil),       // 25: wire.GETDELRes
	(*SETRes)(nil),          // 26: wire.SETRes
	(*DELRes)(nil),          // 27: wire.DELRes
	(*FLUSHDBRes)(nil),      // 28: wire.FLUSHDBRes
	(*KEYSRes)(nil),         // 29: wire.KEYSRes
	(*INCRRes)(nil),         // 30: wire.INCRRes
	(*DECRRes)(nil),         // 31: wire.DECRRes
	(*INCRBYRes)(nil),       // 32: wire.INCRBYRes
	(*DECRBYRes)(nil),       // 33: wire.DECRBYRes
	(*ZElement)(nil),        // 34: wire.ZElement
	(*ZRANGERes)(nil),       // 35: wire.ZRANGERes
	(*ZPOPMAXRes)(nil),      // 36: wire.ZPOPMAXRes
	(*ZREMRes)(nil),         // 37: wire.ZREMRes
	(*ZPOPMINRes)(nil),      // 38: wire.ZPOPMINRes
	(*ZRANKRes)(nil),        // 39: wire.ZRANKRes
	(*ZCARDRes)(nil),        // 40: wire.ZCARDRes
	(*ZRANGEWATCHRes)(nil),  // 41: wire.ZRANGEWATCHRes
	(*ZCOUNTWATCHRes)(nil),  // 42: wire.ZCOUNTWATCHRes
	(*ZCARDWATCHRes)(nil),   // 43: wire.ZCARDWATCHRes
	(*GEOADDRes)(nil),       // 44: wire.GEOADDRes
	(*GEODISTRes)(nil),      // 45: wire.GEODISTRes
	(*GEOCoordinates)(nil),  // 46: wire.GEOCoordinates
	(*GEOElement)(nil),      // 47: wire.GEOElement
	(*GEOSEARCHRes)(nil),    // 48: wire.GEOSEARCHRes
}
var file_protos_res_proto_depIdxs = []int32{
	0,  // 0: wire.Result.status:type_name -> wire.Status
	9,  // 1: wire.Result.TYPERes:type_name -> wire.TYPERes
	10, // 2: wire.Result.PINGRes:type_name -> wire.PINGRes
	19, // 3: wire.Result.ECHORes:type_name -> wire.ECHORes
	21, // 4: wire.Result.HANDSHAKERes:type_name -> wire.HANDSHAKERes
	20, // 5: wire.Result.EXISTSRes:type_name -> wire.EXISTSRes
	22, // 6: wire.Result.GETRes:type_name -> wire.GETRes
	26, // 7: wire.Result.SETRes:type_name -> wire.SETRes
	27, // 8: wire.Result.DELRes:type_name -> wire.DELRes
	29, // 9: wire.Result.KEYSRes:type_name -> wire.KEYSRes
	25, // 10: wire.Result.GETDELRes:type_name -> wire.GETDELRes
	23, // 11: wire.Result.GETEXRes:type_name -> wire.GETEXRes
	24, // 12: wire.Result.GETSETRes:type_name -> wire.GETSETRes
	30, // 13: wire.Result.INCRRes:type_name -> wire.INCRRes
	31, // 14: wire.Result.DECRRes:type_name -> wire.DECRRes
	32, // 15: wire.Result.INCRBYRes:type_name -> wire.INCRBYRes
	33, // 16: wire.Result.DECRBYRes:type_name -> wire.DECRBYRes
	28, // 17: wire.Result.FLUSHDBRes:type_name -> wire.FLUSHDBRes
	16, // 18: wire.Result.EXPIRERes:type_name -> wire.EXPIRERes
	17, // 19: wire.Result.EXPIREATRes:type_name -> wire.EXPIREATRes
	18, // 20: wire.Result.EXPIRETIMERes:type_name -> wire.EXPIRETIMERes
	15, // 21: wire.Result.TTLRes:type_name -> wire.TTLRes
	5,  // 22: wire.Result.GETWATCHRes:type_name -> wire.GETWATCHRes
	6,  // 23: wire.Result.UNWATCHRes:type_name -> wire.UNWATCHRes
	11, // 24: wire.Result.HGETRes:type_name -> wire.HGETRes
	12, // 25: wire.Result.HSETRes:type_name -> wire.HSETRes
	14, // 26: wire.Result.HGETALLRes:type_name -> wire.HGETALLRes
	3,  // 27: wire.Result.HGETWATCHRes:type_name -> wire.HGETWATCHRes
	4,  // 28: wire.Result.HGETALLWATCHRes:type_name -> wire.HGETALLWATCHRes
	7,  // 29: wire.Result.ZADDRes:type_name -> wire.ZADDRes
	8,  // 30: wire.Result.ZCOUNTRes:type_name -> wire.ZCOUNTRes
	35, // 31: wire.Result.ZRANGERes:type_name -> wire.ZRANGERes
	36, // 32: wire.Result.ZPOPMAXRes:type_name -> wire.ZPOPMAXRes
	37, // 33: wire.Result.ZREMRes:type_name -> wire.ZREMRes
	38, // 34: wire.Result.ZPOPMINRes:type_name -> wire.ZPOPMINRes
	39, // 35: wire.Result.ZRANKRes:type_name -> wire.ZRANKRes
	40, // 36: wire.Result.ZCARDRes:type_name -> wire.ZCARDRes
	41, // 37: wire.Result.ZRANGEWATCHRes:type_name -> wire.ZRANGEWATCHRes
	42, // 38: wire.Result.ZCOUNTWATCHRes:type_name -> wire.ZCOUNTWATCHRes
	43, // 39: wire.Result.ZCARDWATCHRes:type_name -> wire.ZCARDWATCHRes
	2,  // 40: wire.Result.ZRANKWATCHRes:type_name -> wire.ZRANKWATCHRes
	44, // 41: wire.Result.GEOADDRes:type_name -> wire.GEOADDRes
	45, // 42: wire.Result.GEODISTRes:type_name -> wire.GEODISTRes
	48, // 43: wire.Result.GEOSEARCHRes:type_name -> wire.GEOSEARCHRes
	13, // 44: wire.HGETALLRes.elements:type_name -> wire.HElement
	34, // 45: wire.ZRANGERes.elements:type_name -> wire.ZElement
	34, // 46: wire.ZPOPMAXRes.elements:type_name -> wire.ZElement
	34, // 47: wire.ZPOPMINRes.elements:type_name -> wire.ZElement
	34, // 48: wire.ZRANKRes.element:type_name -> wire.ZElement
	46, // 49: wire.GEOElement.coordinates:type_name -> wire.GEOCoordinates
	47, // 50: wire.GEOSEARCHRes.elements:type_name -> wire.GEOElement
	51, // [51:51] is the sub-list for method output_type
	51, // [51:51] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_protos_res_proto_init() }
func file_protos_res_proto_init() {
	if File_protos_res_proto != nil {
		return
	}
	file_protos_res_proto_msgTypes[0].OneofWrappers = []any{
		(*Result_TYPERes)(nil),
		(*Result_PINGRes)(nil),
		(*Result_ECHORes)(nil),
		(*Result_HANDSHAKERes)(nil),
		(*Result_EXISTSRes)(nil),
		(*Result_GETRes)(nil),
		(*Result_SETRes)(nil),
		(*Result_DELRes)(nil),
		(*Result_KEYSRes)(nil),
		(*Result_GETDELRes)(nil),
		(*Result_GETEXRes)(nil),
		(*Result_GETSETRes)(nil),
		(*Result_INCRRes)(nil),
		(*Result_DECRRes)(nil),
		(*Result_INCRBYRes)(nil),
		(*Result_DECRBYRes)(nil),
		(*Result_FLUSHDBRes)(nil),
		(*Result_EXPIRERes)(nil),
		(*Result_EXPIREATRes)(nil),
		(*Result_EXPIRETIMERes)(nil),
		(*Result_TTLRes)(nil),
		(*Result_GETWATCHRes)(nil),
		(*Result_UNWATCHRes)(nil),
		(*Result_HGETRes)(nil),
		(*Result_HSETRes)(nil),
		(*Result_HGETALLRes)(nil),
		(*Result_HGETWATCHRes)(nil),
		(*Result_HGETALLWATCHRes)(nil),
		(*Result_ZADDRes)(nil),
		(*Result_ZCOUNTRes)(nil),
		(*Result_ZRANGERes)(nil),
		(*Result_ZPOPMAXRes)(nil),
		(*Result_ZREMRes)(nil),
		(*Result_ZPOPMINRes)(nil),
		(*Result_ZRANKRes)(nil),
		(*Result_ZCARDRes)(nil),
		(*Result_ZRANGEWATCHRes)(nil),
		(*Result_ZCOUNTWATCHRes)(nil),
		(*Result_ZCARDWATCHRes)(nil),
		(*Result_ZRANKWATCHRes)(nil),
		(*Result_GEOADDRes)(nil),
		(*Result_GEODISTRes)(nil),
		(*Result_GEOSEARCHRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_res_proto_rawDesc), len(file_protos_res_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   48,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_res_proto_goTypes,
		DependencyIndexes: file_protos_res_proto_depIdxs,
		EnumInfos:         file_protos_res_proto_enumTypes,
		MessageInfos:      file_protos_res_proto_msgTypes,
	}.Build()
	File_protos_res_proto = out.File
	file_protos_res_proto_goTypes = nil
	file_protos_res_proto_depIdxs = nil
}
