// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.21.12
// source: protos/res.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Err   string                 `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Attrs *structpb.Struct       `protobuf:"bytes,2,opt,name=attrs,proto3" json:"attrs,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*Result_HANDSHAKERes
	//	*Result_GETRes
	//	*Result_SETRes
	//	*Result_KEYSRes
	//	*Result_ZRANGERes
	Response      isResult_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_protos_res_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

func (x *Result) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Result) GetResponse() isResult_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *Result) GetHANDSHAKERes() *HANDSHAKERes {
	if x != nil {
		if x, ok := x.Response.(*Result_HANDSHAKERes); ok {
			return x.HANDSHAKERes
		}
	}
	return nil
}

func (x *Result) GetGETRes() *GETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_GETRes); ok {
			return x.GETRes
		}
	}
	return nil
}

func (x *Result) GetSETRes() *SETRes {
	if x != nil {
		if x, ok := x.Response.(*Result_SETRes); ok {
			return x.SETRes
		}
	}
	return nil
}

func (x *Result) GetKEYSRes() *KEYSRes {
	if x != nil {
		if x, ok := x.Response.(*Result_KEYSRes); ok {
			return x.KEYSRes
		}
	}
	return nil
}

func (x *Result) GetZRANGERes() *ZRANGERes {
	if x != nil {
		if x, ok := x.Response.(*Result_ZRANGERes); ok {
			return x.ZRANGERes
		}
	}
	return nil
}

type isResult_Response interface {
	isResult_Response()
}

type Result_HANDSHAKERes struct {
	HANDSHAKERes *HANDSHAKERes `protobuf:"bytes,10,opt,name=HANDSHAKERes,proto3,oneof"`
}

type Result_GETRes struct {
	GETRes *GETRes `protobuf:"bytes,11,opt,name=GETRes,proto3,oneof"`
}

type Result_SETRes struct {
	SETRes *SETRes `protobuf:"bytes,12,opt,name=SETRes,proto3,oneof"`
}

type Result_KEYSRes struct {
	KEYSRes *KEYSRes `protobuf:"bytes,13,opt,name=KEYSRes,proto3,oneof"`
}

type Result_ZRANGERes struct {
	ZRANGERes *ZRANGERes `protobuf:"bytes,21,opt,name=ZRANGERes,proto3,oneof"`
}

func (*Result_HANDSHAKERes) isResult_Response() {}

func (*Result_GETRes) isResult_Response() {}

func (*Result_SETRes) isResult_Response() {}

func (*Result_KEYSRes) isResult_Response() {}

func (*Result_ZRANGERes) isResult_Response() {}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_Nil
	//	*Value_Str
	//	*Value_I64
	//	*Value_Bytes
	//	*Value_F64
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_protos_res_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{1}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetNil() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_Nil); ok {
			return x.Nil
		}
	}
	return false
}

func (x *Value) GetStr() string {
	if x != nil {
		if x, ok := x.Value.(*Value_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Value) GetI64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_I64); ok {
			return x.I64
		}
	}
	return 0
}

func (x *Value) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *Value) GetF64() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_F64); ok {
			return x.F64
		}
	}
	return 0
}

type isValue_Value interface {
	isValue_Value()
}

type Value_Nil struct {
	Nil bool `protobuf:"varint,1,opt,name=nil,proto3,oneof"`
}

type Value_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

type Value_I64 struct {
	I64 int64 `protobuf:"varint,3,opt,name=i64,proto3,oneof"`
}

type Value_Bytes struct {
	Bytes []byte `protobuf:"bytes,4,opt,name=bytes,proto3,oneof"`
}

type Value_F64 struct {
	F64 float64 `protobuf:"fixed64,5,opt,name=f64,proto3,oneof"`
}

func (*Value_Nil) isValue_Value() {}

func (*Value_Str) isValue_Value() {}

func (*Value_I64) isValue_Value() {}

func (*Value_Bytes) isValue_Value() {}

func (*Value_F64) isValue_Value() {}

type HANDSHAKERes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HANDSHAKERes) Reset() {
	*x = HANDSHAKERes{}
	mi := &file_protos_res_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HANDSHAKERes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HANDSHAKERes) ProtoMessage() {}

func (x *HANDSHAKERes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HANDSHAKERes.ProtoReflect.Descriptor instead.
func (*HANDSHAKERes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{2}
}

type GETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Value                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GETRes) Reset() {
	*x = GETRes{}
	mi := &file_protos_res_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GETRes) ProtoMessage() {}

func (x *GETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GETRes.ProtoReflect.Descriptor instead.
func (*GETRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{3}
}

func (x *GETRes) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type SETRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SETRes) Reset() {
	*x = SETRes{}
	mi := &file_protos_res_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SETRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SETRes) ProtoMessage() {}

func (x *SETRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SETRes.ProtoReflect.Descriptor instead.
func (*SETRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{4}
}

type KEYSRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KEYSRes) Reset() {
	*x = KEYSRes{}
	mi := &file_protos_res_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KEYSRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KEYSRes) ProtoMessage() {}

func (x *KEYSRes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KEYSRes.ProtoReflect.Descriptor instead.
func (*KEYSRes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{5}
}

func (x *KEYSRes) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type ZElement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         int64                  `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZElement) Reset() {
	*x = ZElement{}
	mi := &file_protos_res_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZElement) ProtoMessage() {}

func (x *ZElement) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZElement.ProtoReflect.Descriptor instead.
func (*ZElement) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{6}
}

func (x *ZElement) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ZElement) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type ZRANGERes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*ZElement            `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZRANGERes) Reset() {
	*x = ZRANGERes{}
	mi := &file_protos_res_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZRANGERes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZRANGERes) ProtoMessage() {}

func (x *ZRANGERes) ProtoReflect() protoreflect.Message {
	mi := &file_protos_res_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZRANGERes.ProtoReflect.Descriptor instead.
func (*ZRANGERes) Descriptor() ([]byte, []int) {
	return file_protos_res_proto_rawDescGZIP(), []int{7}
}

func (x *ZRANGERes) GetElements() []*ZElement {
	if x != nil {
		return x.Elements
	}
	return nil
}

var File_protos_res_proto protoreflect.FileDescriptor

var file_protos_res_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x77, 0x69, 0x72, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbb, 0x02, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x65, 0x72, 0x72, 0x12, 0x2d, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x05, 0x61, 0x74, 0x74,
	0x72, 0x73, 0x12, 0x38, 0x0a, 0x0c, 0x48, 0x41, 0x4e, 0x44, 0x53, 0x48, 0x41, 0x4b, 0x45, 0x52,
	0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e,
	0x48, 0x41, 0x4e, 0x44, 0x53, 0x48, 0x41, 0x4b, 0x45, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0c,
	0x48, 0x41, 0x4e, 0x44, 0x53, 0x48, 0x41, 0x4b, 0x45, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06,
	0x47, 0x45, 0x54, 0x52, 0x65, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x77,
	0x69, 0x72, 0x65, 0x2e, 0x47, 0x45, 0x54, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x47, 0x45,
	0x54, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x53, 0x45, 0x54, 0x52, 0x65, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x53, 0x45, 0x54, 0x52,
	0x65, 0x73, 0x48, 0x00, 0x52, 0x06, 0x53, 0x45, 0x54, 0x52, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x07,
	0x4b, 0x45, 0x59, 0x53, 0x52, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x4b, 0x45, 0x59, 0x53, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x07,
	0x4b, 0x45, 0x59, 0x53, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x09, 0x5a, 0x52, 0x41, 0x4e, 0x47,
	0x45, 0x52, 0x65, 0x73, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x77, 0x69, 0x72,
	0x65, 0x2e, 0x5a, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52, 0x09, 0x5a,
	0x52, 0x41, 0x4e, 0x47, 0x45, 0x52, 0x65, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x78, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a,
	0x03, 0x6e, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x03, 0x6e, 0x69,
	0x6c, 0x12, 0x12, 0x0a, 0x03, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x12, 0x0a, 0x03, 0x69, 0x36, 0x34, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x69, 0x36, 0x34, 0x12, 0x16, 0x0a, 0x05, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x03, 0x66, 0x36, 0x34, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00,
	0x52, 0x03, 0x66, 0x36, 0x34, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0e,
	0x0a, 0x0c, 0x48, 0x41, 0x4e, 0x44, 0x53, 0x48, 0x41, 0x4b, 0x45, 0x52, 0x65, 0x73, 0x22, 0x2b,
	0x0a, 0x06, 0x47, 0x45, 0x54, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x08, 0x0a, 0x06, 0x53,
	0x45, 0x54, 0x52, 0x65, 0x73, 0x22, 0x1d, 0x0a, 0x07, 0x4b, 0x45, 0x59, 0x53, 0x52, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x6b, 0x65, 0x79, 0x73, 0x22, 0x38, 0x0a, 0x08, 0x5a, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x37,
	0x0a, 0x09, 0x5a, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x52, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x08, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x77, 0x69, 0x72, 0x65, 0x2e, 0x5a, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x77, 0x69, 0x72,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_res_proto_rawDescOnce sync.Once
	file_protos_res_proto_rawDescData []byte
)

func file_protos_res_proto_rawDescGZIP() []byte {
	file_protos_res_proto_rawDescOnce.Do(func() {
		file_protos_res_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_res_proto_rawDesc), len(file_protos_res_proto_rawDesc)))
	})
	return file_protos_res_proto_rawDescData
}

var file_protos_res_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_res_proto_goTypes = []any{
	(*Result)(nil),          // 0: wire.Result
	(*Value)(nil),           // 1: wire.Value
	(*HANDSHAKERes)(nil),    // 2: wire.HANDSHAKERes
	(*GETRes)(nil),          // 3: wire.GETRes
	(*SETRes)(nil),          // 4: wire.SETRes
	(*KEYSRes)(nil),         // 5: wire.KEYSRes
	(*ZElement)(nil),        // 6: wire.ZElement
	(*ZRANGERes)(nil),       // 7: wire.ZRANGERes
	(*structpb.Struct)(nil), // 8: google.protobuf.Struct
}
var file_protos_res_proto_depIdxs = []int32{
	8, // 0: wire.Result.attrs:type_name -> google.protobuf.Struct
	2, // 1: wire.Result.HANDSHAKERes:type_name -> wire.HANDSHAKERes
	3, // 2: wire.Result.GETRes:type_name -> wire.GETRes
	4, // 3: wire.Result.SETRes:type_name -> wire.SETRes
	5, // 4: wire.Result.KEYSRes:type_name -> wire.KEYSRes
	7, // 5: wire.Result.ZRANGERes:type_name -> wire.ZRANGERes
	1, // 6: wire.GETRes.value:type_name -> wire.Value
	6, // 7: wire.ZRANGERes.elements:type_name -> wire.ZElement
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_protos_res_proto_init() }
func file_protos_res_proto_init() {
	if File_protos_res_proto != nil {
		return
	}
	file_protos_res_proto_msgTypes[0].OneofWrappers = []any{
		(*Result_HANDSHAKERes)(nil),
		(*Result_GETRes)(nil),
		(*Result_SETRes)(nil),
		(*Result_KEYSRes)(nil),
		(*Result_ZRANGERes)(nil),
	}
	file_protos_res_proto_msgTypes[1].OneofWrappers = []any{
		(*Value_Nil)(nil),
		(*Value_Str)(nil),
		(*Value_I64)(nil),
		(*Value_Bytes)(nil),
		(*Value_F64)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_res_proto_rawDesc), len(file_protos_res_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_res_proto_goTypes,
		DependencyIndexes: file_protos_res_proto_depIdxs,
		MessageInfos:      file_protos_res_proto_msgTypes,
	}.Build()
	File_protos_res_proto = out.File
	file_protos_res_proto_goTypes = nil
	file_protos_res_proto_depIdxs = nil
}
